const CREATE_RESOURCE_REQUEST = 'CREATE_RESOURCE_REQUEST'
const CREATE_RESOURCE_REQUEST_SUCCESS = 'CREATE_RESOURCE_REQUEST_SUCCESS'
const CREATE_RESOURCE_REQUEST_ERROR = 'CREATE_RESOURCE_REQUEST_ERROR'

const DELETE_RESOURCE_REQUEST = 'DELETE_RESOURCE_REQUEST'
const DELETE_RESOURCE_REQUEST_SUCCESS = 'DELETE_RESOURCE_REQUEST_SUCCESS'
const DELETE_RESOURCE_REQUEST_ERROR = 'DELETE_RESOURCE_REQUEST_ERROR'

const LIST_RESOURCE_REQUEST = 'LIST_RESOURCE_REQUEST'
const LIST_RESOURCE_REQUEST_SUCCESS = 'LIST_RESOURCE_REQUEST_SUCCESS'
const LIST_RESOURCE_REQUEST_ERROR = 'LIST_RESOURCE_REQUEST_ERROR'
const SELECT_RESOURCE_LIST = 'SELECT_RESOURCE_LIST'

const RETRIEVE_RESOURCE_REQUEST = 'RETRIEVE_RESOURCE_REQUEST'
const RETRIEVE_RESOURCE_REQUEST_SUCCESS = 'RETRIEVE_RESOURCE_REQUEST_SUCCESS'
const RETRIEVE_RESOURCE_REQUEST_ERROR = 'RETRIEVE_RESOURCE_REQUEST_ERROR'
const SELECT_RESOURCE = 'SELECT_RESOURCE'

const UPDATE_RESOURCE_REQUEST = 'UPDATE_RESOURCE_REQUEST'
const UPDATE_RESOURCE_REQUEST_SUCCESS = 'UPDATE_RESOURCE_REQUEST_SUCCESS'
const UPDATE_RESOURCE_REQUEST_ERROR = 'UPDATE_RESOURCE_REQUEST_ERROR'

const DEFAULT_QUERY_LIMIT = 30

module.exports = {
    DEFAULT_QUERY_LIMIT,

    CREATE_RESOURCE_REQUEST,
    CREATE_RESOURCE_REQUEST_SUCCESS,
    CREATE_RESOURCE_REQUEST_ERROR,

    DELETE_RESOURCE_REQUEST,
    DELETE_RESOURCE_REQUEST_SUCCESS,
    DELETE_RESOURCE_REQUEST_ERROR,

    LIST_RESOURCE_REQUEST,
    LIST_RESOURCE_REQUEST_SUCCESS,
    LIST_RESOURCE_REQUEST_ERROR,
    SELECT_RESOURCE_LIST,

    RETRIEVE_RESOURCE_REQUEST,
    RETRIEVE_RESOURCE_REQUEST_SUCCESS,
    RETRIEVE_RESOURCE_REQUEST_ERROR,
    SELECT_RESOURCE,

    UPDATE_RESOURCE_REQUEST,
    UPDATE_RESOURCE_REQUEST_SUCCESS,
    UPDATE_RESOURCE_REQUEST_ERROR,
}
